### ISSUE TITLE
Failed to link with "non-standard" configuration names 

### ISSUE THREAD

**Issue by lucas29252** [pmed/v8-nuget#10]
I have two alternative configurations apart from the typical Debug and Release. They are named "Debug DLL" and "Release DLL" and failed to link throwing a "cannot open input file v8.dll.lib" error.

If I duplicate the folders inside "\packages\v8-$PlatformToolset-$Platform.$Version\lib" and name them "Debug DLL" and "Release DLL" it works like a charm.

**Comment by pmed** [comment]
Yes, because the package has static structure in the `package\lib` directory. I don't know whether it possible to have user-defined configurations in this case.

Your solution with duplicating necessary files works fine because of `$(Configuration)` usage in the package `.props` file. You could also add any configuration-specific properties into that file (e.g. compiler and linker options).
