### ISSUE TITLE
"Cannot open file v8.lib"

### ISSUE THREAD

**Issue by fatcerberus** [pmed/v8-nuget#3]
Just installed v8-v140_xp-x64 in my project, didn't change any project settings, and now get the above error on build.

* MSVS Community 2015 u3
* Win10 Pro

**Comment by fatcerberus** [comment]
This happens for the x86 package too.

**Comment by fatcerberus** [comment]
I figured it out, it looks like the `v140` and `v140_xp` packages are swapped.  My project is using the XP toolset and after I installed v8-v140-x64, it linked properly.

**Comment by pmed** [comment]
Hi @fatcerberus 

That's strange. I've just checked V8 packages with my v8pp project on Visual Studio 2013 and 2015 versions, x86 and x64 targets, both for xp and non-xp toolsets. And all these combinations work as intended:
- when I set the XP toolset (`v120_xp` or `v140_xp`) in a "General" section of the project options, and then I have to install an appropriate package:
  - on `Win32` platform: `v8-v120_xp-x86` or `v8-v140_xp-x86`
  - on `x64` platform: `v8-v120_xp-x64` or `v8-v140_xp-x64`
- for non-XP toolset (`v120` or `v140`):
  - on `Win32` platform: `v8-v120-x86` or `v8-v140-x86`
  - on `x64` platform: `v8-v120-x64` or `v8-v140-x64`

I've done all the checks in a clean solution, with no other packages installed before.

When the required V8 package is missing, I get an error "Cannot open include file: 'v8.h': No such file or directory" instead of the error about absent v8.lib.

**Comment by fatcerberus** [comment]
Huh.  Something must be screwed up with my solution file or MSVC installation then.  Last night I had another problem too: It couldn't find the include files.  I finally had to resort to copying the files out of the packages directory and referencing them manually.

I'll see what happens with a fresh solution.

**Comment by fatcerberus** [comment]
Something must be wrong on my end - regardless of which package I install, it fails at compile time with "cannot open include file v8.h".  Not sure what's going on, but the V8 packages themselves doesn't seem to be at fault.

I'll report back if I find out anything else.

**Comment by maliming** [comment]
i have the same problem
WIN10 VS2015 XP toolset : can't open v8.h

**Comment by padjon** [comment]
I have the same issue: can't open v8.h
Win10 VS15 v140 Toolset

**Comment by padjon** [comment]
Some additional input:

Adding the include folder manually (packages\v8-v140-x86.5.6.326.55\include in my case) fixes it for me. no dependencies or anything else to add.

**Comment by pmed** [comment]
This issue is still unreproducible on my side, both with existing and fresh project.

Please check that you have installed the proper version of package, depending on the Platform and Toolset version used, as described in a comment above https://github.com/pmed/v8-nuget/issues/3#issuecomment-261187239

**Comment by padjon** [comment]
I did, added even all packages at one time for testing purposes.
My current setup is to have the v140 x86 installed and manually add the include folder. Everything else works then by no manual modifications. Libs are copied correctly.

**Comment by fatcerberus** [comment]
Same issue with MSVC 2017:
![Imgur](http://i.imgur.com/cBAC6Sc.png)

No modifications were made to the project after installing the packages, this was immediately after installing them and attempting to build.

**Comment by padjon** [comment]
I noticed, the import issue happens for me because of other property sheets which defined additional include paths without the option "inherit from parent o project defaults".
if i remove these sheets or activate the option, the includes are recognized.

This might help for reproducing @pmed

**Comment by fatcerberus** [comment]
Hm, that could be the case for me then, my project uses Allegro which has its own property sheet.

**Comment by pmed** [comment]
Thank you, @padjon

Yes, it seems other property sheets with overriding include/library path settings may be the issue cause.
