### ISSUE TITLE
Can't build under Win7x64, VS2015

### ISSUE THREAD

**Issue by viktorcpp** [pmed/v8-nuget#6]
Hello
Could you help please with next issue:
Under Win7 x64, VS2015, Python27
Tryed VCINSTALLDIR
this 'c:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/'
and 'c:/Program Files (x86)/Microsoft Visual Studio 14.0/'
And got the same errors on build.py - https://puu.sh/zX00i/7cd26bd53a.png

![output](https://user-images.githubusercontent.com/1128037/38390169-2acb2e1c-3929-11e8-9e86-212d380828d9.png)

I would be grateful for your help

**Comment by pmed** [comment]
Hi @viktorcpp 

The issue was due to outdated GN.exe. I've updated it, but it seems that recent V8 versions do not support Visual Studio 2015 builds. At least I can build V8 version 6.7 only with Visual Studio 2017.

For VS2015 I've got errors in `constexpr` functions:

> D:\Projects\v8-nuget\v8\src/base/bits.h(88): error C3250: 'upper_half': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(97): note: see reference to function template instantiation 'unsigned int v8::base::bits::CountLeadingZeros<uint32_t,32>(T)' being compiled
        with
        [
            T=uint32_t
        ]
D:\Projects\v8-nuget\v8\src/base/bits.h(89): error C3250: 'next_value': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(90): error C3250: 'add': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(91): error C3250: 'next_bits': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(92): error C3256: 'next_value': variable use does not produce a constant expression
D:\Projects\v8-nuget\v8\src/base/bits.h(92): error C3256: 'add': variable use does not produce a constant expression
D:\Projects\v8-nuget\v8\src/base/bits.h(76): error C3259: 'constexpr' functions can only have one return statement
D:\Projects\v8-nuget\v8\src/base/bits.h(120): error C3250: 'u': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(126): note: see reference to function template instantiation 'unsigned int v8::base::bits::CountTrailingZeros<uint32_t,32>(T)' being compiled
        with
        [
            T=uint32_t
        ]
D:\Projects\v8-nuget\v8\src/base/bits.h(121): error C3256: 'u': variable use does not produce a constant expression
[20/1020] CXX obj/v8_libbase/once.obj
ninja: build stopped: subcommand failed.
