### ISSUE TITLE
please update to 6.4.388.14 or above

### ISSUE THREAD

**Issue by JerrySievert** [pmed/v8-nuget#7]
I've had a request to merge in changes to plv8 to allow for easier msvc compilation - this relies on nuget (see https://github.com/plv8/plv8/pull/239).

I'm hesitant to do this until v8-nuget is updated to 6.4.388.14 or above, since this is the version that mitigates spectre and meltdown (see: https://chromium-review.googlesource.com/c/v8/v8/+/848921 and https://github.com/v8/v8/commit/a060a4fc565aa40fcb3acb6b075936b78b38fc10), and plv8 is currently patched to above this version.

plv8 is also pegged to the version that node is using: 6.4.388.40, but I'm ok with a minor difference as long as it's at 6.4.388.14 or above.

any chance of getting this updated?

thanks!

**Comment by pmed** [comment]
Hi @JerrySievert 

I've updated V8 package to 6.7.288.40  version, but only for for Visual Studio 2017. Unfortunately, it seems that recent V8 versions do not support building with  Visual Studio 2015 and older.

**Comment by JerrySievert** [comment]
hi @pmed - that's awesome, thanks!  we ended up going with a build-in-place method for the time being, but it seems to work on other versions of visual studio, wondering what method you're using to build, and what problems you're running into?

this is the method we're using in plv8:

```
git checkout 6.4.388.40
gclient sync
tools\dev\v8gen.py x64.release -- is_component_build=true v8_use_snapshot=true v8_use_external_startup_data=false v8_enable_i18n_support=false
ninja -C out.gn\x64.release d8
```

**Comment by pmed** [comment]
I'm using `build.py` script from this repository in a command line window with `vcvarsall.bat` invoked. The script doesn't use `gclient` and `depot_tools`, so it might be a source of the issue, because `depot_tools` could use another C++ toolset for V8 building.

On building V8 version 6.4 with Visual C++ 2015 I've got these build errors:

> D:\Projects\v8-nuget\v8\src/base/bits.h(88): error C3250: 'upper_half': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(97): note: see reference to function template instantiation 'unsigned int v8::base::bits::CountLeadingZeros<uint32_t,32>(T)' being compiled
        with
        [
            T=uint32_t
        ]
D:\Projects\v8-nuget\v8\src/base/bits.h(89): error C3250: 'next_value': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(90): error C3250: 'add': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(91): error C3250: 'next_bits': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(92): error C3256: 'next_value': variable use does not produce a constant expression
D:\Projects\v8-nuget\v8\src/base/bits.h(92): error C3256: 'add': variable use does not produce a constant expression
D:\Projects\v8-nuget\v8\src/base/bits.h(76): error C3259: 'constexpr' functions can only have one return statement
D:\Projects\v8-nuget\v8\src/base/bits.h(120): error C3250: 'u': declaration is not allowed in 'constexpr' function body
D:\Projects\v8-nuget\v8\src/base/bits.h(126): note: see reference to function template instantiation 'unsigned int v8::base::bits::CountTrailingZeros<uint32_t,32>(T)' being compiled
        with
        [
            T=uint32_t
        ]
D:\Projects\v8-nuget\v8\src/base/bits.h(121): error C3256: 'u': variable use does not produce a constant expression
[14/1001] ACTION //:js2c(//build/toolchain/win:x86)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Projects\v8-nuget\build.py", line 127, in <module>
    subprocess.check_call([NINJA, '-C', out_dir, 'v8'], cwd='v8', env=env)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\\Projects\\v8-nuget\\bin\\ninja.exe', '-C', 'out.gn\\v140\\x86\\Debug', 'v8']' returned non-zero exit status 1

It seems due that Visual C++ 2015 has partial `constexpr` support.

**Comment by JerrySievert** [comment]
you nailed it - VS2015 and lower do not have complete C++14 support, which v8 is relying more on.

`depot_tools` does download its own compiler if it needs to, which should be a-ok, as the resulting dll's will be compatible.

I don't know if that's necessarily a solution for you, or maybe check for VS version and run `depot_tools` if need be?

**Comment by pmed** [comment]
Jerry, thank you for the information!

I will stick with the `build.py` script, since VS2015 support is not very actual for me. Maybe I will try to use Clang frontend with VS2015 toolset.

The initial goal of this project was to speedup V8 builds, by avoiding `gclient` and `fetch` invocation, just pulling only necessary v8 sources and dependencies.
